#ifndef _MSG_QUEUE_OPCODE_H_
#define _MSG_QUEUE_OPCODE_H_

enum {
	MSG_OP_NORMAL =0,
	MSG_OP_PLAY,
	MSG_OP_INIT ,
	MSG_OP_PAUSE,
	MSG_OP_PAUSE_NET,
	MSG_OP_RESUME,
	MSG_OP_RESUME_NET,
	MSG_OP_START,
	MSG_OP_START_NET,
	MSG_OP_STOP,
	MSG_OP_STOP_NET,
	MSG_OP_UPDATE_CONFIG,
	MSG_OP_CAPTURE,
	MSG_OP_NEXTFILE,
	MSG_OP_EXIT,//10
	MSG_OP_SEEK,
	MSG_OP_SEEK_NET,
	MSG_OP_DISHSTOP,
	MSG_OP_DISP_ADJUST,
	MSG_OP_EMC,
	MSG_OP_LDW,
	MSG_OP_FCW,
	MSG_OP_FRAME_SKIPPING,
	MSG_OP_MOTION_DET,
	MSG_OP_PCD //parking collicion dection
};

#endif

